@baseUrl=http://localhost:3000

# @name ReadAllMessages
GET {{baseUrl}}/messages
?limit=10
&offset=1

### 

# @name ReadEspecificMessage
GET {{baseUrl}}/messages/1

### 

# @name CreateMessage
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "Novo recado",
  "of": "Júlia",
  "to": "Felipe",
  "read": false,
  "date": "2024-10-09T22:41:57.408Z"
}
###

# @name UpdateMessage
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

{
  "text": "Recado atualizado",
  "of": "Júlia",
  "to": "Felipe",
  "read": false,
  "date": "2024-10-09T22:41:57.408Z"
}

###

# @name DeleteMessage
DELETE {{baseUrl}}/messages/1
