@baseUrl=http://localhost:3000

# @name ReadAllMessages
GET {{baseUrl}}/messages
?limit=10
&offset=1

### 

# @name ReadEspecificMessage
GET {{baseUrl}}/messages/1

### 

# @name CreateMessage
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "message": "This is a message",
  "user":"Felipe"
}
###

# @name UpdateMessage
PATCH {{baseUrl}}/messages/333
Content-Type: application/json

{
  "message": "This is a message",
  "user":"Júlia"
}

###

# @name DeleteMessage
DELETE {{baseUrl}}/messages/1
